### ISSUE TITLE
[Feature Request] Change QR Code color scheme

### ISSUE THREAD

**Issue by springpeeace** [TobiasPSP/Modules.QRCodeGenerator#11]
Hello,

can you guys add feature to change colors of QR code ? It seems that there are hardcoded 2 colorschemes directly in base64 string in loader.psm1, darkColorRgba and lightColorRgba. Or am I doing something badly ?

This is not issue and I hope I am not the only one person who could use that :D

This is awesome tool, nice work!! 
PS: I am new to the github, please excuse my post if its wrong

**Comment by T0biii** [comment]
I opend a PR #12 for this. In my testing it works as expected.

example: `New-PSOneQRCodeText -Text "test-text" -Width 100 -Show -darkColorRgba @(0,255,0) -lightColorRgba @(255,0,255)`
Where `-darkColorRgba` is lime in my example and `-lightColorRgba` is pink
![image](https://user-images.githubusercontent.com/5702338/126400101-c42af5f1-6fef-42a5-84d2-99f8d81efe5b.png)

PS: Welcome to GitHub

**Comment by TobiasPSP** [comment]
published version 2.6 to PSGallery
