### ISSUE TITLE
base64 content in loader.psm1 is flagged as Malware Name: Heur.BZC.PZQ.Pantera.18.F8E7C08D

### ISSUE THREAD

**Issue by lansalot** [TobiasPSP/Modules.QRCodeGenerator#17]
As it says on the header, BitDefender isn't happy about that content, will submit to them for further analysis, but that's a bit worrying...

**Comment by TobiasPSP** [comment]
I haven't changed this part of the code in years, so it's funny to see BitDefender suddenly change its mind. Maybe part of the binary sequence has been seen in true malware. I can only guess. 
Let me know if you find anything substantial. I love AV engines but what worries me a bit is how relatively light-heartedly some of them incriminate legit code.

**Comment by TobiasPSP** [comment]
Seems to be a common problem: https://stackoverflow.com/questions/58530046/bitdefender-says-code-insiders-download-has-heur-bzc-nzf-pantera-7-37c58ef0

**Comment by lansalot** [comment]
I'd said to my colleague that spotted it, that it's possibly the long base64 decoding that sets the alarm off... will update if ti get a response tho !

Incidentally, the same thing happened to me with an older BurntToast module the other day
