### ISSUE TITLE
return base64 qr code

### ISSUE THREAD

**Issue by WagoL** [TobiasPSP/Modules.QRCodeGenerator#18]
Possible to get the base64 of the QR code instead of a png.
I tried with this. Alas doesn't work. I'm also way outside my comfort zone.

```
    $b64Data = New-Object -TypeName QRCoder.Base64QRCode -ArgumentList ($data);
    $b64Str = $b64Data.GetGraphic(20)
New-Object : Cannot find type [QRCoder.Base64QRCode]: verify that the assembly containing this type is loaded.
```

**Comment by TobiasPSP** [comment]
What would you like to achieve? If you just want to convert the text to base64, you could call the appropriate .net methods, i.e. like explained here: https://adsecurity.org/?p=478

**Comment by WagoL** [comment]
I would like to have the QR code returned as a base64 string instead of file that is written to disk.

**Comment by TobiasPSP** [comment]
Ok but then what? Would you want to take the base64 encoded byte array of the qr code image to save the file elsewhere? Just trying to understand so I can come up with the best suggestion.

**Comment by WagoL** [comment]
When I generate New-QRCodeWifiAccess I would like to have the base64 byte array returned. So when I send an email I can include this base64 string in the html body. Hopes this clarifies things.

**Comment by TobiasPSP** [comment]
Ok.
Here is where you get your hands on the final byte array:
https://github.com/TobiasPSP/Modules.QRCodeGenerator/blob/03f63911f99e80786d5f72396f2fb5d89afac432/QRCodeGenerator/2.6.0/New-PSOneQRCode.ps1#L64
Next, all you would need to do is feed the byte array to the .NET method that encodes it in base64.

**Comment by TobiasPSP** [comment]
There are many examples on doing the actual base64 encoding on the web, i.e. here (random pick): https://shellgeek.com/powershell-base64-encoding/

**Comment by TobiasPSP** [comment]
Essentially, you take the byte array that I pointed you to, then feed it into the encoding method - done.

**Comment by WagoL** [comment]
That does the job. Thanks for pointing it out. I just was confused as the .NET QRCode class has a base64 renderer.

**Comment by TobiasPSP** [comment]
Glad this helped!
