### ISSUE TITLE
New-QRCodeWifiAccess example incorrect

### ISSUE THREAD

**Issue by jfrmilner** [TobiasPSP/Modules.QRCodeGenerator#2]
Noticed a minor issue

`Get-Help New-QRCodeWifiAccess -Examples`

`New-PSOneQRCodeGeoLocation -SSID InternetCafe -Longitude TopSecret123 -Width 200 -Show -OutPath "$home\Desktop\qr.png"`

Should be

`New-QRCodeWifiAccess -SSID InternetCafe -Password TopSecret123 -Width 200 -Show -OutPath "$home\Desktop\qr.png"`

**Comment by T0biii** [comment]
nice catch. I can change it with #1 later
or I open a New PR
