### ISSUE TITLE
[Feature Request] I have a new suggestion, generating URI QR codes

### ISSUE THREAD

**Issue by j81blog** [TobiasPSP/Modules.QRCodeGenerator#3]
I found the following function very usefull, it was missing form your functions:

'''Powershell
function New-PSOneQRCodeURI
{
    <#
        .SYNOPSIS
        Creates a QR code graphic containing a URI
        .DESCRIPTION
        Creates a QR code graphic in png format that - when scanned by a smart device - opens a URI/URL in your webapp
        .PARAMETER URI
        The URI
        .PARAMETER Width
        Height and Width of generated graphics (in pixels). Default is 100.
        .PARAMETER Show
        Opens the generated QR code in associated program
        .PARAMETER OutPath
        Path to generated png file. When omitted, a temporary file name is used.
        .EXAMPLE
        New-PSOneQRCodeURI -URI "https://github.com/TobiasPSP/Modules.QRCodeGenerator" -Width 50 -Show -OutPath "$home\Desktop\qr.png"
        Creates a QR code png graphics on your desktop, and opens it with the associated program
        .NOTES
        Compatible with all PowerShell versions including PowerShell 6/Core
        Uses binaries from https://github.com/codebude/QRCoder/wiki
        .LINK
        https://github.com/TobiasPSP/Modules.QRCodeGenerator
    #>

    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [alias("URL")]
        [System.Uri]
        $URI,

        [ValidateRange(10,2000)]
        [int]
        $Width = 100,

        [Switch]
        $Show,

        [string]
        $OutPath = "$env:temp\qrcode.png"
    )
        
    $payload = @"
$($URI.AbsoluteUri)
"@

    $generator = New-Object -TypeName QRCoder.QRCodeGenerator
    $data = $generator.CreateQrCode($payload, 'Q')
    $code = new-object -TypeName QRCoder.PngByteQRCode -ArgumentList ($data)
    $byteArray = $code.GetGraphic($Width)
    [System.IO.File]::WriteAllBytes($outPath, $byteArray)

    if ($Show) { Invoke-Item -Path $outPath }
}
'''

**Comment by T0biii** [comment]
oh forgot to write "closes" in the commit :(
Now it has to be closed manually

**Comment by TobiasPSP** [comment]
I am busy in other projects right now so I can't wrap my head around it :-) If you forgot something, simply do another pull request and I integrate it and update the gallery

**Comment by T0biii** [comment]
no its fine :) if you add "closes" in the commit message followed by the number the issue has it get closes automaticly if the commit get merged in the main branch

you only need to close this issue now :)

**Comment by T0biii** [comment]
Still needs to get closed @TobiasPSP
