### ISSUE TITLE
Version on PowerShellGallery

### ISSUE THREAD

**Issue by Pyromane** [TobiasPSP/Modules.QRCodeGenerator#4]
Hello,

thanks for the extremely useful extension!
Unfortunately, only the 2.2 version is available on the PowerShellGallery.

greetings

**Comment by T0biii** [comment]
Yeah the owner want to make some more changes bevor publishing the New Version..

**Comment by Pyromane** [comment]
Thanks for the answer.
Unfortunately I couldn't find the info anywhere.

**Comment by T0biii** [comment]
> Thanks for the answer.
> Unfortunately I couldn't find the info anywhere.

Yea you right.. 
i wrote him an Email thats where I got the Info

**Comment by T0biii** [comment]
@Pyromane see #5
