### ISSUE TITLE
2.2 doesn't seem to include New-PSOneQRCodeText

### ISSUE THREAD

**Issue by mcnods** [TobiasPSP/Modules.QRCodeGenerator#5]
I'm a new user and I was able to get this working in-session for powershell, but it doesn't persist after I restart the app.

I cannot call New-PSOneQRCodeText after installing fresh from nuget with version 2.2. Is there a chance that could be re-added as a built-in call?

**Comment by T0biii** [comment]
in Version 2.3 this Command(New-PSOneQRCodeText) was added, see also #4

**Comment by mcnods** [comment]
Ok, thank you! I only see version 2.2 and below here: https://www.powershellgallery.com/packages/QRCodeGenerator/

How can I get 2.3? Is there another source I should use?

**Comment by T0biii** [comment]
You can only clone(download) this repo 
And copy the files from the folder (https://github.com/TobiasPSP/Modules.QRCodeGenerator/tree/master/QRCodeGenerator/2.3) and put in manully in the PowerShell Modules Folder

or you wait until the owner @TobiasPSP pushes the Version 2.3 to the PowerShell Gallery

**Comment by mcnods** [comment]
Thanks again! I was able to get it working flawlessly that way :)

**Comment by danbuntu** [comment]
Hello @TobiasPSP is there any news on version 2.3 being pushed to the powershell gallery?
We're very keen to use the New-PsOneQRCodeText function. Whilst we have installed it manually via the instructions provided above it difficult to then move this into production.

**Comment by TobiasPSP** [comment]
Version 2.4.0 was just added to the Gallery. Can you double-check to see if this version works for you?
