### ISSUE TITLE
Payload size limit?

### ISSUE THREAD

**Issue by iborghoff** [TobiasPSP/Modules.QRCodeGenerator#9]
Is there a size limit for the payload passed to the New-PSOneQRCode function? 

I'm trying trying to pass a payload which is around 4002 characters, and when running the function I get the following error messages:

Exception calling "CreateQrCode" with "2" argument(s): "Sequence contains no elements"
At line:59 char:5
+     $data = $generator.CreateQrCode($payload, 'Q')
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

Exception calling "GetGraphic" with "1" argument(s): "Object reference not set to an instance of an object."
At line:61 char:5
+     $byteArray = $code.GetGraphic($Width)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException

Exception calling "WriteAllBytes" with "2" argument(s): "Value cannot be null.
Parameter name: bytes"
At line:62 char:5
+     [System.IO.File]::WriteAllBytes($outPath, $byteArray)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

**Comment by TobiasPSP** [comment]
Only the first exception matters. The others are follow-up errors. Can you verify that $payload actually has content? The exception seems to indicate that it is empty.

**Comment by iborghoff** [comment]
I took the function and modified it to pass in a device serial number and hash:

$payload = @"
Serial number: $($csv.'Device Serial Number')
Device hash: $($csv.'Hardware Hash')
"@ 

The output of which would be:

Serial number = 1223434
Device hash = T0HQAgEAHAAAAAoAFQNhSgAACgAkA2FKYFK5JwQCCQ..........(etc.)

If I remove the second line of the payload it works, which made me think it was a character limit of the second line.

**Comment by TobiasPSP** [comment]
I justvtested, and yes there seems to be a payload limit, based on the text you are wrapping. Which makes sense because there is a physical limit of how much information a QR code with a given size can represent.

**Comment by TobiasPSP** [comment]
In my test, the limit kicked in at around 1600 chars, depending on the actusl text a bit.

**Comment by iborghoff** [comment]
Having a read up on the standards and it appears its possible, but maybe the QRCoder binary doesn't support it. I'll keep digging! Many thanks for your help!
